"use strict";
const get = (id) => document.getElementById(id);
let report = null;
const fmt = (n) => new Intl.NumberFormat().format(n);
const safe = (value) => value.replace(/[&<>"']/g, (char) => ({
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#39;",
})[char]);
const demoReport = {
    privacy: "Synthetic demo data · no packet payloads",
    summary: { total: 4, forwarded: 2, dropped: 2 },
    flows: [
        {
            host: "github.com",
            application: "GitHub",
            packets: 1,
            bytes: 86,
            verdict: "ALLOW",
            reason: "Explicit domain allow rule",
        },
        {
            host: "example-blocked.test",
            application: "HTTP",
            packets: 1,
            bytes: 128,
            verdict: "DROP",
            reason: "Domain block rule",
        },
        {
            host: "",
            application: "UDP",
            packets: 1,
            bytes: 60,
            verdict: "DROP",
            reason: "IP block rule",
        },
        {
            host: "github.com",
            application: "DNS",
            packets: 1,
            bytes: 70,
            verdict: "ALLOW",
            reason: "No blocking rule matched",
        },
    ],
};
function render() {
    if (!report)
        return;
    get("total").textContent = fmt(report.summary.total);
    get("forwarded").textContent = fmt(report.summary.forwarded);
    get("dropped").textContent = fmt(report.summary.dropped);
    get("flowCount").textContent = fmt(report.flows.length);
    get("state").textContent = "Report loaded";
    get("privacy").textContent = report.privacy;
    const rate = report.summary.total
        ? Math.round((report.summary.dropped / report.summary.total) * 100)
        : 0;
    get("donut").style.background =
        `conic-gradient(var(--red) ${rate}%,#162033 0)`;
    get("donut").querySelector("b").textContent = rate + "%";
    get("legend").innerHTML =
        `<span>● ${fmt(report.summary.forwarded)} allowed</span><span>● ${fmt(report.summary.dropped)} dropped</span>`;
    const groups = new Map();
    report.flows.forEach((f) => groups.set(f.application, (groups.get(f.application) || 0) + f.bytes));
    const top = [...groups].sort((a, b) => b[1] - a[1]).slice(0, 8), max = Math.max(...top.map((x) => x[1]), 1);
    get("apps").innerHTML = top
        .map(([name, value]) => `<div class="bar-row"><span>${safe(name)}</span><div><i style="width:${(value / max) * 100}%"></i></div><b>${fmt(value)}</b></div>`)
        .join("");
    renderRows();
}
function renderRows() {
    if (!report)
        return;
    const q = get("search").value.toLowerCase();
    const rows = report.flows.filter((f) => (f.host + " " + f.application + " " + f.verdict + " " + f.reason)
        .toLowerCase()
        .includes(q));
    get("rows").innerHTML =
        rows
            .map((f) => `<tr><td>${safe(f.application)}</td><td>${safe(f.host || "—")}</td><td>${fmt(f.packets)}</td><td>${fmt(f.bytes)}</td><td class="${f.verdict.toLowerCase()}">${f.verdict}</td><td>${safe(f.reason || "No rule matched")}</td></tr>`)
            .join("") || '<tr><td colspan="6">No matching flows.</td></tr>';
}
get("file").onchange = async (e) => {
    const file = e.target.files?.[0];
    if (!file)
        return;
    try {
        report = JSON.parse(await file.text());
        if (!report.summary || !Array.isArray(report.flows))
            throw new Error();
        render();
    }
    catch {
        get("state").textContent = "Invalid report";
        get("privacy").textContent = "Choose a report generated by SentinelDPI";
    }
};
get("search").oninput = renderRows;
get("demo").onclick = () => {
    report = demoReport;
    render();
};
const aiMessages = get("axiomMessages");
const addMessage = (role, text) => {
    const item = document.createElement("div");
    item.className = `ai-message ${role}`;
    item.textContent = text;
    aiMessages.append(item);
    aiMessages.scrollTop = aiMessages.scrollHeight;
};
const offlineAnswer = (question) => {
    if (!report)
        return "Load a SentinelDPI report first so I can inspect its flow metadata.";
    const drops = report.flows.filter((flow) => flow.verdict === "DROP");
    const top = [...report.flows].sort((a, b) => b.bytes - a.bytes)[0];
    if (/rule/i.test(question)) {
        const hosts = [...new Set(drops.map((flow) => flow.host).filter(Boolean))];
        return hosts.length
            ? `Review before applying:\n${hosts.map((host) => `block_domain=${host}`).join("\n")}\n\nThese are suggestions only; confirm each domain is unwanted.`
            : "There are no dropped domains from which to propose a domain rule.";
    }
    if (/drop|block/i.test(question)) {
        return drops.length
            ? `${drops.length} flow(s) were dropped:\n${drops.map((flow) => `• ${flow.application} ${flow.host || "unknown host"}: ${flow.reason}`).join("\n")}`
            : "No flows were dropped in this report.";
    }
    return `Report summary: ${report.summary.total} packets, ${report.summary.forwarded} forwarded and ${report.summary.dropped} dropped across ${report.flows.length} flows.${top ? ` The largest flow is ${top.application} (${top.bytes} bytes).` : ""}`;
};
const askAxiom = async (question) => {
    addMessage("user", question);
    const mode = get("axiomMode");
    mode.textContent = "ANALYZING…";
    try {
        const response = await fetch("/api/axiom", {
            method: "POST",
            headers: { "content-type": "application/json" },
            body: JSON.stringify({ question, report }),
        });
        if (!response.ok)
            throw new Error();
        const payload = (await response.json());
        addMessage("assistant", payload.answer);
        mode.textContent = payload.mode.toUpperCase();
    }
    catch {
        addMessage("assistant", offlineAnswer(question));
        mode.textContent = "OFFLINE ANALYST";
    }
};
get("axiomForm").onsubmit = (event) => {
    event.preventDefault();
    const input = get("axiomInput");
    const question = input.value.trim();
    if (!question)
        return;
    input.value = "";
    void askAxiom(question);
};
document.querySelectorAll("[data-prompt]").forEach((button) => {
    button.onclick = () => void askAxiom(button.dataset.prompt || "Summarize this report.");
});
fetch("/api/health")
    .then((response) => response.json())
    .then((data) => {
    get("axiomMode").textContent = data.ai ? data.provider.toUpperCase() : "OFFLINE ANALYST";
})
    .catch(() => (get("axiomMode").textContent = "OFFLINE ANALYST"));
