#include "sentinel/engine.hpp"
#include "sentinel/parser.hpp"
#include <algorithm>
#include <atomic>
#include <chrono>
#include <fstream>
#include <iomanip>
#include <thread>

namespace sentinel { namespace {std::string json_escape(const std::string&s){std::string o;for(char c:s){if(c=='"'||c=='\\'){o+='\\';o+=c;}else if(c=='\n')o+="\\n";else if(c!='\r')o+=c;}return o;}std::string masked(uint32_t ip,bool anon){return anon?ip_to_string(ip&0xffffff00)+"/24":ip_to_string(ip);}}
DpiEngine::DpiEngine(RuleEngine rules,EngineOptions options):rules_(std::move(rules)),options_(options){if(options_.workers==0)options_.workers=1;}
EngineStats DpiEngine::process(const std::filesystem::path&input,const std::filesystem::path&output){auto start=std::chrono::steady_clock::now();PcapReader reader(input);auto packets=reader.read_all();std::vector<bool> keep(packets.size(),true);std::atomic_size_t next{0};stats_={};flows_.clear();std::vector<std::thread> pool;for(size_t worker=0;worker<options_.workers;worker++)pool.emplace_back([&]{while(true){size_t i=next.fetch_add(1);if(i>=packets.size())break;auto parsed=PacketParser::parse(packets[i]);RuleDecision decision;if(parsed.valid)decision=rules_.decide(parsed);keep[i]=decision.verdict==Verdict::Allow;std::lock_guard lock(mutex_);stats_.total++;stats_.bytes+=packets[i].bytes.size();if(parsed.valid){stats_.parsed++;auto key=canonical_flow(parsed);auto&flow=flows_[key];flow.key=key;flow.packets++;flow.bytes+=packets[i].bytes.size();if(!parsed.host.empty())flow.host=parsed.host;flow.application=parsed.application;if(decision.verdict==Verdict::Drop){flow.verdict=Verdict::Drop;flow.reason=decision.reason;}}if(keep[i])stats_.forwarded++;else stats_.dropped++;}});for(auto&t:pool)t.join();PcapWriter writer(output);for(size_t i=0;i<packets.size();i++)if(keep[i])writer.write(packets[i]);flow_snapshot_.clear();for(const auto&[_,flow]:flows_)flow_snapshot_.push_back(flow);std::sort(flow_snapshot_.begin(),flow_snapshot_.end(),[](const auto&a,const auto&b){return a.bytes>b.bytes;});stats_.elapsed_ms=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count();return stats_;}
void DpiEngine::write_json_report(const std::filesystem::path&path)const{std::ofstream o(path);o<<"{\n  \"generator\": \"SentinelDPI by Sudesh Mehar\",\n  \"privacy\": \"Offline analysis; report addresses "<<(options_.anonymize_report?"anonymized":"visible")<<"\",\n  \"summary\": {\"total\": "<<stats_.total<<", \"parsed\": "<<stats_.parsed<<", \"forwarded\": "<<stats_.forwarded<<", \"dropped\": "<<stats_.dropped<<", \"bytes\": "<<stats_.bytes<<", \"elapsedMs\": "<<std::fixed<<std::setprecision(2)<<stats_.elapsed_ms<<"},\n  \"flows\": [\n";for(size_t i=0;i<flow_snapshot_.size();i++){const auto&f=flow_snapshot_[i];o<<"    {\"source\": \""<<masked(f.key.first.ip,options_.anonymize_report)<<":"<<f.key.first.port<<"\", \"destination\": \""<<masked(f.key.second.ip,options_.anonymize_report)<<":"<<f.key.second.port<<"\", \"protocol\": "<<int(f.key.protocol)<<", \"host\": \""<<json_escape(f.host)<<"\", \"application\": \""<<json_escape(f.application)<<"\", \"packets\": "<<f.packets<<", \"bytes\": "<<f.bytes<<", \"verdict\": \""<<(f.verdict==Verdict::Drop?"DROP":"ALLOW")<<"\", \"reason\": \""<<json_escape(f.reason)<<"\"}"<<(i+1<flow_snapshot_.size()?",":"")<<"\n";}o<<"  ]\n}\n";}
void DpiEngine::write_csv_report(const std::filesystem::path&path)const{std::ofstream o(path);o<<"source,destination,protocol,host,application,packets,bytes,verdict,reason\n";for(const auto&f:flow_snapshot_)o<<masked(f.key.first.ip,options_.anonymize_report)<<':'<<f.key.first.port<<','<<masked(f.key.second.ip,options_.anonymize_report)<<':'<<f.key.second.port<<','<<int(f.key.protocol)<<",\""<<f.host<<"\",\""<<f.application<<"\","<<f.packets<<','<<f.bytes<<','<<(f.verdict==Verdict::Drop?"DROP":"ALLOW")<<",\""<<f.reason<<"\"\n";}
}
