#include "sentinel/parser.hpp"
#include <algorithm>
#include <cctype>
#include <cstring>
#include <sstream>

namespace sentinel {
namespace {uint16_t be16(const uint8_t*p){return uint16_t(p[0])<<8|p[1];}uint32_t be32(const uint8_t*p){return uint32_t(p[0])<<24|uint32_t(p[1])<<16|uint32_t(p[2])<<8|p[3];}std::string lower(std::string s){std::transform(s.begin(),s.end(),s.begin(),[](unsigned char c){return char(std::tolower(c));});return s;}}
size_t FlowKeyHash::operator()(const FlowKey&k)const noexcept{size_t h=k.first.ip;h=(h*1315423911u)^k.second.ip;h=(h*31)^k.first.port;h=(h*31)^k.second.port;return(h*31)^k.protocol;}
std::string ip_to_string(uint32_t ip){std::ostringstream s;s<<(ip>>24)<<'.'<<((ip>>16)&255)<<'.'<<((ip>>8)&255)<<'.'<<(ip&255);return s.str();}
FlowKey canonical_flow(const ParsedPacket&p){Endpoint a{p.source_ip,p.source_port},b{p.destination_ip,p.destination_port};if(b<a)std::swap(a,b);return{a,b,uint8_t(p.protocol)};}
ParsedPacket PacketParser::parse(const PacketRecord&r){ParsedPacket p;if(r.bytes.size()<34||be16(r.bytes.data()+12)!=0x0800)return p;const size_t ip=14;const uint8_t ihl=(r.bytes[ip]&0x0f)*4;if(ihl<20||r.bytes.size()<ip+ihl)return p;p.source_ip=be32(r.bytes.data()+ip+12);p.destination_ip=be32(r.bytes.data()+ip+16);p.protocol=Protocol(r.bytes[ip+9]);size_t transport=ip+ihl;if(p.protocol==Protocol::TCP){if(r.bytes.size()<transport+20)return p;p.source_port=be16(r.bytes.data()+transport);p.destination_port=be16(r.bytes.data()+transport+2);size_t h=(r.bytes[transport+12]>>4)*4;if(h<20||r.bytes.size()<transport+h)return p;p.payload_offset=transport+h;}else if(p.protocol==Protocol::UDP){if(r.bytes.size()<transport+8)return p;p.source_port=be16(r.bytes.data()+transport);p.destination_port=be16(r.bytes.data()+transport+2);p.payload_offset=transport+8;}else{p.payload_offset=transport;}p.payload_length=r.bytes.size()-p.payload_offset;std::span<const uint8_t> payload(r.bytes.data()+p.payload_offset,p.payload_length);if(p.protocol==Protocol::TCP&&(p.source_port==443||p.destination_port==443))p.host=extract_tls_sni(payload);if(p.host.empty()&&p.protocol==Protocol::TCP&&(p.source_port==80||p.destination_port==80))p.host=extract_http_host(payload);if(p.host.empty()&&p.protocol==Protocol::UDP&&(p.source_port==53||p.destination_port==53))p.host=extract_dns_name(payload);p.application=classify(p.host,p.destination_port,p.protocol);p.valid=true;return p;}
std::string PacketParser::extract_http_host(std::span<const uint8_t>d){if(d.empty())return{};std::string text((char*)d.data(),std::min<size_t>(d.size(),8192));std::string low=lower(text);auto pos=low.find("\r\nhost:");if(pos==std::string::npos&&low.rfind("host:",0)!=0)return{};pos=low.rfind("host:",0)==0?5:pos+7;while(pos<text.size()&&std::isspace((unsigned char)text[pos]))pos++;auto end=text.find_first_of("\r\n",pos);return lower(text.substr(pos,end-pos));}
std::string PacketParser::extract_dns_name(std::span<const uint8_t>d){if(d.size()<13)return{};size_t pos=12;std::string name;for(int labels=0;labels<32&&pos<d.size();labels++){uint8_t n=d[pos++];if(n==0)break;if((n&0xc0)||pos+n>d.size())return{};if(!name.empty())name+='.';name.append((char*)d.data()+pos,n);pos+=n;}return lower(name);}
std::string PacketParser::extract_tls_sni(std::span<const uint8_t>d){if(d.size()<9||d[0]!=0x16||d[5]!=0x01)return{};size_t pos=9;if(pos+34>d.size())return{};pos+=34;if(pos>=d.size())return{};pos+=1+d[pos];if(pos+2>d.size())return{};size_t suites=be16(d.data()+pos);pos+=2+suites;if(pos>=d.size())return{};pos+=1+d[pos];if(pos+2>d.size())return{};size_t total=be16(d.data()+pos);pos+=2;size_t end=std::min(d.size(),pos+total);while(pos+4<=end){uint16_t type=be16(d.data()+pos),len=be16(d.data()+pos+2);pos+=4;if(pos+len>end)return{};if(type==0&&len>=5){size_t q=pos+2;if(q+3>end)return{};uint16_t host_len=be16(d.data()+q+1);q+=3;if(q+host_len<=end)return lower(std::string((char*)d.data()+q,host_len));}pos+=len;}return{};}
std::string PacketParser::classify(std::string_view h,uint16_t port,Protocol proto){std::string host=lower(std::string(h));if(host.find("youtube")!=std::string::npos||host.find("googlevideo")!=std::string::npos)return"YouTube";if(host.find("netflix")!=std::string::npos)return"Netflix";if(host.find("facebook")!=std::string::npos||host.find("instagram")!=std::string::npos)return"Meta";if(host.find("github")!=std::string::npos)return"GitHub";if(host.find("google")!=std::string::npos)return"Google";if(port==53)return"DNS";if(port==443)return"HTTPS";if(port==80)return"HTTP";if(proto==Protocol::UDP)return"UDP";if(proto==Protocol::TCP)return"TCP";return"Other";}
}
